# Generated by Django 5.0.4 on 2024-11-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybud', '0003_topic_room_host_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
