# Generated by Django 5.0.4 on 2024-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybud', '0005_room_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_pdfs/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
